on: [push]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: spyoungtech/mirror-action@master
        if: github.repository == 'pikokr/chino-rewrite'
        with:
          REMOTE: 'https://github.com/TeamEnd/chino-rewrite'
          GIT_USERNAME: pikokr
          GIT_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
